# /**************************************************************
#  * Class:  CSC-615-01 Fall 2022
#  * Name: Emanuel Francis
#  * Student ID: 917491268
#  * Github ID: Emanuelf-sfsu
#  * Project: Assignment 2 - Tapeless Ruler
#  *
#  * File: Francis_Emanuel_tapeless_ruler.c
#  *
#  * Description:This program is going to measure distance using 
#  * the Echo Sensor (HC-SR04) and display distance
#  * in centimeters in your terminal.
#  *
#  **************************************************************/
all: assignment2

assignment2: Francis_Emanuel_tapeless_ruler.c	
	gcc -o assignment2  Francis_Emanuel_tapeless_ruler.c -lpigpio -lrt
